INSERT INTO contents (level_id, content, theme_id)
VALUES(1, 'I am too shy to speak to that many people.', 1),
(2, 'In a wonderful day at the zoo, we saw lions, tigers, bears and exotic birds.', 1),
(3, 'He helped her travel the world around her as she breathed in the essence of Mother Nature. Love was in the air as the leaf got blown by the wind.', 1),
(4, 'A Victory Medal displayed proudly on his chest. Scarred hands coaxed sorrowful notes from an old violin. Pennies scattered in the case at his feet.', 1),
(5, 'A boy turned off his buzzing alarm. He got out of bed and went outside and got his cloak on and became a superhero, saving people that were in trouble.', 1),
(6, 'His dream job was operating the hot dog slingshot from the golf cart roof, the crowd cheering as their sixth inning hero rounded the baseball field. He was grateful to have the goods this time.', 1),
(7, 'The man was not happy at all. He had just come back from a long walk where he had spent the majority of his time trying to coax young squirrels out of their nests. Perplexed, he went off to bed', 1),
(8, 'How many gumdrops is enough? After having eaten so many candies that she was sick, the little girl cried for her mom. Halloween can be very hard on a young childs stomach. Her dear old mother prepared some flat gingerale to help soothe her upset tummy', 1),
(9, 'The old man sat outside, whiskey in hand. Thoughts drifting to memories. That time, those stories, that other time, those other stories. He smiles. Memories of when whiskey wasn’t trendy. Memories of a time when memories were only told through memories. His smile widens. Ah yes, memories of memories.', 1)
(10, 'As I looked at the music sheet smiling I saw the notes dancing to an intricate and beautiful dance. I looked away for a second for someone had called my name, but when I turned back, the notes were back into the sheet.  All that was left was one note that fell on my palm'.),
(11, 'Wrinkles everywhere, who was that woman looking back at me from the bathroom mirror? Don’t recognise the face and I haven’t got grey hair, well except for maybe the odd one or two. Is that laughter lines or even more wrinkles? Oh look the start of a moustache, nah that’s got to be somebody else. I’m in the wrong bathroom!', 1),
(12, 'Once upon a time I lived in a deep dark forest. The canopy of trees stopped the light from ever reaching the moss covered floor. Half of me wanted to leave and never come back, but the other part of me enjoyed the solitude. I enjoyed living amongst the dark creatures that called the forest their home. The animals would often leave their burrows to keep me company', 1)
